### ISSUE TITLE
[DatabaseRequest]:Delete Study Definitions

### ISSUE THREAD

**Issue by pgoel-ent** [transcelerate/ddf-sdr-support#10]
### Environment

Demo

### Description

can you delete the following ids?

58386c05-644e-4ec9-894d-961ad030c6f7
2c3ca517-58f4-499d-a14a-3ef71c39c457
8df783b9-a6d5-48bd-b0bc-04ef15afeb76
77cef2a0-b9aa-4feb-9b02-97b6d0f2ef51

**Comment by sdr-support** [comment]
@pgoel-ent  Your request has been acknowledged. We shall update once all the requested definitions are deleted. 
Kindly note this will be a permanent delete and all versions of these studies will be deleted.

**Comment by Viswesh-Mb** [comment]
@pgoel-ent Kindly be noted, the above mentioned definitions are deleted.
