### ISSUE TITLE
[DatabaseRequest]: Delete Studies

### ISSUE THREAD

**Issue by pardekumar** [transcelerate/ddf-sdr-support#16]
### Environment

Demo

### Description

Please delete following studies

1a2db3f2-418d-4970-9793-4be1fa0c9272
2dea2beb-ca9b-4bc6-bb03-39499a6b470c
9e07f2fa-a22c-4cfe-b5e6-e3af2451047c
11693f16-900e-4234-9202-16b32cafa02b
1b3e7b33-7e8d-48ba-89c8-f37d41457119
2d2bf476-9b6d-4be1-8ab9-512b0961d7a2
c98ee40b-8c65-495d-94fc-5221fd5c94b2
3e5ba26c-f6a3-4381-a4b5-75bae54e57c8
e32168d9-7c64-43ee-bcc4-d36a20cf7338
39c68776-8c13-4537-9f13-d97e2aa791fc
05bca618-5cb5-40ce-9303-a6b7e8cad237
24f114ad-334f-4766-bcfc-b7b02b05f6c2
8b64668c-f64c-430f-b948-0f9f05d9ec56
ccfe6788-e1cc-4ee5-93fc-5ffa17e6234c
110fcd45-6eb1-4c32-99fa-c23ce66f2097
7d117a67-da99-42b9-b33b-95fab8b1356e

**Comment by sdr-support** [comment]
@pardekumar Request acknowledged. Ticket shall be updated once all the studies are deleted. Please note all versions of the given study IDs will be deleted & this is a permanent deletion.

**Comment by Viswesh-Mb** [comment]
@pardekumar The study definitions with the above mentioned uuids are deleted as requested.
