### ISSUE TITLE
[TechSupport]: Array of UUIDs not accepted

### ISSUE THREAD

**Issue by sdr-support** [transcelerate/ddf-sdr-support#18]
### Technical Support Details

Frederik has noticed that the SDR schema has the following possible sub-schemas for the encounters[]:

 

We have successfully posted studies with the full #/components/schemas/Encounter def’n, but an array of uuid strings like the following partial sample fails:

                            "encounters": [
                                "72335b0b-59e6-35f3-b8c3-c5bd7d4ac167",
                                "7cba39a2-6530-3423-a8b0-4fd5a8c93594",
                                "1b205be4-0072-3bf2-8835-0a2deda23e22"
                            ]

That returned:

_{
    "statusCode": "400",
    "message": "Invalid Input",
    "error": {
        "clinicalStudy.studyDesigns[0].studyCells[0].studyEpoch.encounters[0]": [
            "Error converting value \"fa15a475-5506-3987-9225-2cffdb3c58df\" to type 'TransCelerate.SDR.Core.DTO.StudyV1.EncounterDto'. Path 'clinicalStudy.studyDesigns[0].studyCells[0].studyEpoch.encounters[0]', line 279, position 70."
        ],_

Can you explain why the array of uuids was not accepted ?

### Choose the option

API

### Environment

Demo

**Comment by sdr-support** [comment]
The data for encounters element should be an array of encounter schema items, which means each array item should contain all mandatory properties of the encounter schema along with uuid’s.

Please refer the sample JSON document link mentioned below and let us know if still have any questions.

https://github.com/transcelerate/ddf-sdr-api/blob/main/DataModel/API_UserGuide_JSON_Files/Request-POST-AddStudyDefinitionV1.json

**Comment by nigama-swaminathan** [comment]
User to refer API user guide to see what was implemented in Reference Implementation as opposed to CDISC RI and accordingly pass Study Definition JSON.
