### ISSUE TITLE
[TechSupport]: 400 HTTP Status for adding study definition (SDR Host Migration)

### ISSUE THREAD

**Issue by pdbaumhart** [transcelerate/ddf-sdr-support#20]
### Technical Support Details

The team has deployed our own environment, following the deployment and configuration documentation. We are now experiencing issues with API requests when trying to post a study definition (i.e., `POST /api/v1/studydefinitions`). 

## Expected Behavior

Return a 201 status with the response body for [POST - Add Study Definitionsv1](https://github.com/transcelerate/ddf-sdr-api/blob/main/DataModel/API_UserGuide_JSON_Files/Response-POST-AddStudyDefinitionV1.json). 

## Current Behavior

Submitting the [Request Body for POST - Add New Study DefinitionV1](https://github.com/transcelerate/ddf-sdr-api/blob/main/DataModel/API_UserGuide_JSON_Files/Request-POST-AddStudyDefinitionV1.json) returns an HTTP 400 status 
```json
{
    "statusCode": "400",
    "message": "An Error Occured"
}
```

### Postman Screenshot
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/64853409/190748168-98ee3c6b-f8b0-44cc-92d3-2c9cc9092870.png">

## Possible Solution

- Need steps to gain adjust log-level for our API deployment
- Need steps to gain access to fine-grained application logs for our API deployment
- Identify application error from logs to allow for more troubleshooting

## Steps to Reproduce

1. Create a Postman request pointing to the APIM url for `/api/v1/studydefinitions`
2. Get an Auth token and include it in the headers for the `Authorization` key-value pair
3. Insert the contents of [Request Body for POST - Add New Study DefinitionV1](https://github.com/transcelerate/ddf-sdr-api/blob/main/DataModel/API_UserGuide_JSON_Files/Request-POST-AddStudyDefinitionV1.json) returns an HTTP 400 status 
4. Submit the request 

**Please Note**: Due to firewall issues I am not able to give you direct access to our environment. My team can schedule a call in order to support the work. 

### Choose the option

API

**Comment by sdr-support** [comment]
Issue acknowledged. Please let us know a suitable time to connect on Sept 19 (please mention timezone when proposing time).

**Comment by sdr-support** [comment]
Scheduling this call to troubleshoot the issues with API requests when trying to post a study definition.
________________________________________________________________________________ 
Microsoft Teams meeting 
Join on your computer, mobile app or room device 
[Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZDg0N2ZhNWEtOGUwYi00ODgwLTliMmYtMTIwYjA2MzNlNGM1%40thread.v2/0?context=%7b%22Tid%22%3a%22e0793d39-0939-496d-b129-198edd916feb%22%2c%22Oid%22%3a%220899b653-e92e-44bb-8ae6-e0e283dce08b%22%7d) 
Meeting ID: 272 415 673 441 
Passcode: HrYNNZ 
[Download Teams](https://www.microsoft.com/en-us/microsoft-teams/download-app) | [Join on the web](https://www.microsoft.com/microsoft-teams/join-a-meeting)
Join with a video conferencing device 
From Accenture Videoconference Device (VTC) Dial 123. From Non-Accenture Videoconference device dial 123@connect.accenture.com 
Video Conference ID: 111 479 044 30 
[Alternate VTC instructions](https://in.accenture.com/videoconferencing/join-a-video-interoperability-meeting/) 
[Learn More](https://aka.ms/JoinTeamsMeeting) | [Meeting options](https://teams.microsoft.com/meetingOptions/?organizerId=0899b653-e92e-44bb-8ae6-e0e283dce08b&tenantId=e0793d39-0939-496d-b129-198edd916feb&threadId=19_meeting_ZDg0N2ZhNWEtOGUwYi00ODgwLTliMmYtMTIwYjA2MzNlNGM1@thread.v2&messageId=0&language=en-US) 
________________________________________________________________________________

**Comment by pdbaumhart** [comment]
@sdr-support we were able to self-resolve and inspect the logs. The underlying issue was due to incorrectly setting the `ConnectionStrings--DatabaseName` secret in the Key Vault
