### ISSUE TITLE
[DatabaseRequest]: Delete studies created for testing

### ISSUE THREAD

**Issue by pardekumar** [transcelerate/ddf-sdr-support#21]
### Environment

Demo

### Description

Delete following studies created for testing

dab2bc20-8fcd-4cec-97f8-512230e29310
8aae089b-ac69-4dbf-bdb7-4c127aeda653
3d6a6908-d8f9-4735-ab23-ee418fe94d35
3ae52d2d-9bf0-4bf0-a409-92461af14af0
e104ec4c-6006-426e-967f-3c7016db55d2

**Comment by pardekumar** [comment]
Delete this one also

6b31835f-f033-4b5c-8e55-b48ab8ff1bb7

**Comment by Viswesh-Mb** [comment]
@pardekumar The study definitions with the above mentioned uuids are deleted as requested.
