### ISSUE TITLE
[TechSupport]: Running locally without authentication? 

### ISSUE THREAD

**Issue by sdr-support** [transcelerate/ddf-sdr-support#27]
### Technical Support Details

We are trying to run the whole ddf-sdr system (db, api and ui) on a local machine.
When attempting to run the ui, we have issues with authentication.
Is there a way to disable the authentication? If not, is that something that could be implemented?
This would make it much easier for developers or anyone wanting to try out the app.

[https://github.com/transcelerate/ddf-sdr-ui/issues/100](url)

### Choose the option

UI

### Environment

None

**Comment by sdr-support** [comment]
@HEnquist

**Comment by HEnquist** [comment]
This very first attempt was done without having the API running at all. We got stuck on the authentication and never got to the point where the UI tried to send a request to the API.

**Comment by sdr-support** [comment]
@HEnquist Please find below a temporary way to bypass authentication. Nonetheless, your recommendation has been considered to make code configurable to bypass authentication and added to our backlog. 

 - Comment the addition of protected resources in app-module.constants.ts as shown below - 
![image](https://user-images.githubusercontent.com/109733800/221844082-ae1503c1-33b9-4208-9079-09eba4ec073c.png)
- In app-routing.module.ts remove all the msalguard from the routes as shown below 
![image](https://user-images.githubusercontent.com/109733800/221845272-49b24320-9e00-44e7-9cae-0559f5b07960.png)

- Additionally, in recent-activity.component.ts please comment out the lines in ngOnInit as below and add some dummy values for local storage items related to login.
![image](https://user-images.githubusercontent.com/109733800/221845695-f15589a8-54db-49cb-8b85-66117833ab33.png)

- Finally, you can change the URL in api-url-constants.ts to say /v1/studydefinitions etc. instead of api/ui/ OR alternatively, change the application URL in the .NET Web API launchSettings.json to include api/ui/ in the localhost applicationURL.

Once all the above changes have been done, you can run ng serve and directly navigate to Home URL - https://localhost:4200/home

Let us know if you face any other issues.

**Comment by HEnquist** [comment]
Thank you so much for the very clear instructions! I got it running right away.
This workaround works perfectly for now, but having a config option for disabling the authentication would be much appreciated.

**Comment by sdr-support** [comment]
Thank you @HEnquist. Your feedback has been documented in our backlog for making auth-bypass configurable.
For any further queries / support please log your tickets [here](https://github.com/transcelerate/ddf-sdr-support/issues/new/choose)

Closing the issue as per confirmation.
