### ISSUE TITLE
[AccessRequest]:

### ISSUE THREAD

**Issue by bluesman** [transcelerate/ddf-sdr-support#33]
### Full Name

Tom Walpole

### Company Name

ZS Associates

### Environment

Demo

### Terms of Use and Privacy Policy

- [X] I agree to the [Terms of Use and Privacy Policy](https://transcelerate.github.io/ddf-sdr-support/TermsandCondition.html).

**Comment by sdr-support** [comment]
@bluesman Thank you for your request. The current user request process is under review and this request form will be updated. We shall close this issue and inform as soon as the new request process has been rolled-out. 
Kindly look for email communication from TransCelerate / Accenture for the same in upcoming weeks.
