### ISSUE TITLE
[TechSupport]: SDR UI - Package installation is failed

### ISSUE THREAD

**Issue by InduSekharSajja** [transcelerate/ddf-sdr-support#38]
### Technical Support Details

Hello, I'd like to test this study builder UI, but I'm facing a problem.

Based on your README, I ran "npm install" command in SDR-WebApp directory.
But, installation was failed by some errors as bellow.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @azure/msal-angular@2.0.5
npm ERR! Found: rxjs@7.4.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.4.0" from the root project
npm ERR!   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/cdk@13.3.7
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^13.1.1" from the root project
npm ERR!     peer @angular/cdk@"13.3.7" from @angular/material@13.3.7
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^13.3.7" from the root project
npm ERR!   8 more (@angular/common, @angular/core, @angular/forms, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.0.0" from @azure/msal-angular@2.0.5
npm ERR! node_modules/@azure/msal-angular
npm ERR!   @azure/msal-angular@"^2.0.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: rxjs@6.6.7
npm ERR! node_modules/rxjs
npm ERR!   peer rxjs@"^6.0.0" from @azure/msal-angular@2.0.5
npm ERR!   node_modules/@azure/msal-angular
npm ERR!     @azure/msal-angular@"^2.0.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I tried "main" and "release" branches, but I got same error.
Do you have some solutions ?

My environment:
* Windows 10
* npm -v >> 9.5.1
* node -v >> v18.16.0
 

### Choose the option

UI

**Comment by sdr-support** [comment]
Please find below steps to resolve the issues - 

1. Delete SDR-WebApp\package-lock.json
2. Run npm install --force
3. Run ng build (Ensure angular cli is installed and scripts running is enabled in system)

**Comment by sdr-support** [comment]
@seyama-daisuke : Please try the workaround mentioned in previous comment and let us know.

**Comment by seyama-daisuke** [comment]
@sdr-support 
Sorry for late response.
I was able to complete the installation by your W.A. Thank you so much.

And I will close this issue.

BTW, I am facing new errors after ng build command. But, this will other issue.

**Comment by sdr-support** [comment]
@seyama-daisuke : 

Thanks for the confirmation. Please raise a new issue [here](https://github.com/transcelerate/ddf-sdr-support/issues/new/choose) with the exact build error details.
