### ISSUE TITLE
[AccessRequest]:

### ISSUE THREAD

**Issue by pardekumar** [transcelerate/ddf-sdr-support#5]
### Full Name

Pardeep Kumar

### Company Name

Deloitte

### Environment

Demo

### Additional Comments

Please provide the access

**Comment by sdr-support** [comment]
@pardekumar : We have already sent the invite to your Deloitte email address. Please accept the invite.

Also, we received certificate from Shilp Kumar from your organization. Once the certificate is configured in SDR Demo environment, we will respond over email and then you will be able to communicate to SDR system.

**Comment by pardekumar** [comment]
I am able to access SDR Web Application (UI) and SDR API Root URL

**Comment by pardekumar** [comment]
In this case, we need not to setup our own Azure Infra and App, we can use your setup (SDR Web Application and SDR API) for PUSH/GET requests for Connectathon, please so confirm

**Comment by sdr-support** [comment]
> I am able to access SDR Web Application (UI) and SDR API Root URL

Thank you for confirming. We shall close this ticket. For any further queries, please raise a support ticker [here](https://github.com/transcelerate/ddf-sdr-support/issues/new?assignees=sdr-support&labels=techSupport&template=TechSupport.yml&title=%5BTechSupport%5D%3A)
