### ISSUE TITLE
[DatabaseRequest]: Delete  Study Definitions

### ISSUE THREAD

**Issue by nigama-swaminathan** [transcelerate/ddf-sdr-support#8]
### Environment

Demo

### Description

can you delete the following ids?

["9c2272e0-5e3b-49c5-b9da-43e66840f0ed", "f6065a10-9c09-466c-82a2-315fc0a66fd8", "7a50b6c1-3bd8-4bab-a138-de9159ba4e4a", "06a28a20-a192-417b-87e3-ea9f24da8278", "23327261-1afb-4ba8-a46d-0c23a5deee75", "bc7ed308-6de3-4505-9451-756245692939"]

**Comment by nigama-swaminathan** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/NIGAMA~1.SWA/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/NIGAMA~1.SWA/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/NIGAMA~1.SWA/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:36.0pt;word-wrap:break-word'>




UUID | Study Title | Study Type | Latest SDR   Upload Version
-- | -- | -- | --
9c2272e0-5e3b-49c5-b9da-43e66840f0ed | Phase 2 Study of ISIS 681257 (AKCEA-APO(a)-LRx) in Participants With Hyperlipoproteinemia(a) and Cardiovascular Disease | treatment study | 1
f6065a10-9c09-466c-82a2-315fc0a66fd8 | Phase 2 Study of ISIS 681257 (AKCEA-APO(a)-LRx) in Participants With Hyperlipoproteinemia(a) and Cardiovascular Disease | treatment study | 1
7a50b6c1-3bd8-4bab-a138-de9159ba4e4a | Phase 2 Study of ISIS 681257 (AKCEA-APO(a)-LRx) in Participants With Hyperlipoproteinemia(a) and Cardiovascular Disease | treatment study | 1
06a28a20-a192-417b-87e3-ea9f24da8278 | Phase 2 Study of ISIS 681257 (AKCEA-APO(a)-LRx) in Participants With Hyperlipoproteinemia(a) and Cardiovascular Disease | treatment study | 1
23327261-1afb-4ba8-a46d-0c23a5deee75 | Phase 2 Study of ISIS 681257 (AKCEA-APO(a)-LRx) in Participants With Hyperlipoproteinemia(a) and Cardiovascular Disease aaa | treatment study | 4
bc7ed308-6de3-4505-9451-756245692939 | Phase 2 Study of ISIS 681257 (AKCEA-APO(a)-LRx) in Participants With Hyperlipoproteinemia(a) and Cardiovascular Disease | INTERVENTIONAL | 13




</body>

</html>

**Comment by Viswesh-Mb** [comment]
The above mentioned studies are deleted from the database.
